[package]
name = "pq-eddsa"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PQ-EdDSA R_det relation on Binius64"

[dependencies]
ed25519-binius = { path = "../ed25519" }
binius-core.workspace = true
binius-frontend.workspace = true
binius-circuits.workspace = true
num-bigint.workspace = true
anyhow.workspace = true
